language: node_js
node_js:
- 0.12
- 0.1
services:
- mongodb
env:
  matrix:
  - MONGOLAB_URI=mongodb://localhost:27017/prolifiko
  global:
  - secure: uBIgIqqMA0iK4pcWTkjx+dss0mh7URuR+zCkufbC2V6L94MkGJEC10XSC7nl8OScGS4Vv0HcfSshQVOaHFXr9ZBNRCGtS7fGOdxOb+xQ1so0MrjaoqugjeFE+0d/MgAKJGDMfkyTJZMt7+//fi9klRWdSXo9cN0t7TJoppmqGJXywF9fCpwKixTsjUwFJQeqSVO7PA3YKbYcer3sf1yJlB+x7QU18Lq6RxzNfwKB2LUNYRTpAE8NkKApiWWAQKIpubwPMJc1ReMPbt+ezx8UfgD6WVi/8v2uSQ5PsdtxsZlcbTl4HLGkQAGLIbpQwi8XSvYmNxs6GA8EtmDXJ4sssyjCfcJrZopvFmNbBUE/dXW5zQmuFwjo7c/OXEEHOGiaLO1EeCK1Rl3D+XAHFUFH523PvLM6DAdBQpPbFEe4cuoMC1N36UPRLPriIrdHaIKQDvV/5dJfYEONFiY1sMIZJr9yBYndE8bMpZWK8OOKptmjBEnK0H3pNWyaa1Zjqd+qg3UZYJ4USWDlCo/nFggCG89fuFALuRBE2+pUWwGJ+Yj4sXo4TT07PVmgevtKy3Qav8ifxVh3dd6UVTQpzU/hVbsR6OefwATmZYcjigCcAwGibXHERhngp2t75jaYGLWYBC/uk6sH0wr6G+mVvHwRRv3Sa0RY+HHryu3IXmIczho=
  - secure: LDKXQLL+vYku1TpxZSqu25Y6rh/VRsN5KjjFv1sA6raHhRIsy2aJHtbbRQtcfupyJU+AnvH190ExHGGON/Sz2w8I83+m1pYbH9dz7Fh67Njee7X5KUKG2IPYGiouYv5+YiyT0PKDePH9g0wM66HNLGScdOXzccIh9zT1Vt0uFHkid1nIvppVspOgv/y8H7npZ0lL8r5wbrc4olTrAzk1S2Fd8AHRYsW4bLN1zPmkD5Qt5Kn729V4M+n08prhRh34UcYV/Kf5tSj/NWaG4hsVcG8bno8LkQFkNCARQG+XPONOcW3b07LFySZpsr3GT913TKRBMJ3elWFwl/mh24uF1LSUAHxCzVdoMR89oh1ZBVlRZUbftbQYyfRS2+34B/517hmwqSKtJjcmjV7BCU0vurW6nAE4Nh/sxdfJSGPKnL0CneXLEHjjcZ9aBAgbUWDLifYAUx9GPwyRpzBBcAFPe82aSBnySzFHgYV1MFIkTJYWlVhUoG4LxrshVM7MUq7d/uUZ4kd8Q1YsOWs1I9mzcJZo+TTgr6m4eMUSiP0yC9l4WlxFpAgWaD/0jwEQWqOClhynPyUfuvkHBSmEbePvLLOnx2ndVI+Y9lsCEFj3B65fGGTjIgAFT7pGrCKG+azUyx2VUtmToyRIBRZMgmLjVac8IkTKqYQ2SrDIh2gUzAk=
