language: node_js
node_js:
- 0.12
- 0.1
services:
- mongodb
env:
  matrix:
  - MONGOLAB_URI=mongodb://localhost:27017/prolifiko
  global:
    secure: Phwg0f9dgy2pGZfcRdBorKF3nAvmHF6r9ZeKRb/xO4STT7KIE4txS91HcXGTFNXZx1rQRUIUmdYs2BYT7zu282UuhVXNRKSQeschWevZMyMT6Ti8IBxYzg7FqQmwVaL9INPewyfv5CpRyXfH6L7CZ1hqCdVBzA/bG+g3vagqWijtypN5xETOiX9dvDUPgpxfQEm2Y6sPd6H3LSbxgvtc7L9XVBdZHEg3wf4YyM/XDDDvRdmkHXOb1vT+eG10XQ7SExCgdsqx2ZdR5thSXVip0phNkKWA/mWZq42OQDj6LjYSDcDdofJ3bypZ4T+LfvpUVwh349UApDOiDQSNhcFjy9Oz+giS3cUermBzDpkFPcyX4V/J/vOZNf5uKqVV4kUme+EN1jr4mLQWd1uOg6dNn33tudWARP76ICWSo+/Na4Z4hQPJ3iZu3jBsiynx1bsMEvbddpYxbStptm0lYbyJycY2ORuWBRR2GdfOEhT0EkjUorYMiOdutl5aBvo36ZZqLuij/fI/O0aXZMHEBPTg0lFSvO+pfDVsDUCGRqcJJ+IukktUJBWAh33UPGOwuAOGxXRCnpNsrHpH8GF7XFG+qm9fp/wqdUSJBq5v0eWTKpWgBRQN/0dOxkdOfqSHOsDGIZ7JdzX68GC2yw6D4E4Fcdyhr2JUXcVBow0DpoX1cYk=
